[package]
name = "hashbin"
version = "0.1.0"
edition = "2021"
authors = ["fadhilsaheer"]
repository = "https://github.com/octoi/hashbin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.1.2"
